version: '3.9'

services:
  api:
    build:
      context: ./api
      network: host
    container_name: otus-highload-api
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app/src
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
  database:
    image: postgres:15
    container_name: otus-highload-db
    hostname: otus-highload-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  cargo-target: {}
  pgdata: {}
  cargo-cache: {}
